<h2>Predict Titanic Survival</h2>
<p>The RMS Titanic set sail on its maiden voyage in 1912, crossing the Atlantic from Southampton, England to New York City. The ship never completed the voyage, sinking to the bottom of the Atlantic Ocean after hitting an iceberg, bringing down 1,502 of 2,224 passengers onboard.

In this project you will create a Logistic Regression model that predicts which passengers survived the sinking of the Titanic, based on features like age and class.

The data we will be using for training our model is provided by Kaggle. Feel free to make the model better on your own and submit it to <a href ='https://www.kaggle.com/c/titanic'> the Kaggle Titanic competition!<a/></p>

<p>followed by Codecademy's instructuon</p>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
#load and inspect titanic data
passenger = pd.read_csv('train.csv')

In [4]:
print(passenger.head())
print(len(passenger))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
89

<p>Let’s take a look at Age. Print passengers['Age'].values. You can see we have multiple missing values, or nans. Fill all the empty Age values in passengers with the mean age.</P>

In [5]:
#I am going to focus on gender and age columns on each data
#change the value on Sex columns male:0 female:1
passenger['Sex'] = passenger['Sex'].map({'male':0,'female':1})
#inspect Age column
print(passenger['Age'])
# There are some missing values, so I need to clean those null values.
passenger['Age'].fillna(value = round(passenger['Age'].mean()),inplace=True)


0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64


<p>Given the strict class system onboard the Titanic, let’s utilize the Pclass column,
or the passenger class, as another feature. Create a new column named FirstClass that stores 1 
for all passengers in first class and 0 for all other passengers.</p>
<p>Create a new column named SecondClass that stores 1 for all passengers in second class and 0 for all other passengers.
Print passengers and inspect the DataFrame to ensure all the updates have been made.</p>


In [6]:
passenger['FirstClass'] = passenger['Pclass'].apply(lambda i: 1 if i == 1 else 0)
passenger['SecondClass'] = passenger['Pclass'].apply(lambda i: 1 if i ==2 else 0)

<h2>Select and Split the Data</h2>
<p>Now that we have cleaned our data, let’s select the columns we want to build our model on. Select columns Sex, Age, FirstClass, and SecondClass and store them in a variable named features. Select column Survived and store it a variable named survival.</p>

In [7]:
features = passenger[[ 'Sex', 'Age', 'FirstClass', 'SecondClass' ]]
survival = passenger['Survived']
features.isna().any()
survival.isna().any()

False

<p>Split the data into training and test sets using sklearn‘s train_test_split() method. We’ll use the training set to train the model and the test set to evaluate the model.</p>

In [8]:
X_train,X_test,y_train,y_test = train_test_split(features,survival)

<h2>Normalize the Data</h2>
<p>Since sklearn‘s Logistic Regression implementation uses Regularization, we need to scale our feature data.
Create a StandardScaler object, .fit_transform() it on the training features, and .transform() the test features.</p>

In [9]:
scaler = StandardScaler()
train_fuature = scaler.fit_transform(X_train)
test_fuature = scaler.transform(X_test)


<h3>Create and Evaluate the Model</h3>
<p>Create a LogisticRegression model with sklearn and .fit() it on the training data.
Fitting the model will perform gradient descent to find the feature coefficients that minimize the log-loss for the training data.</p>

In [10]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

<p>.score() the model on the training data and print the training score.

Scoring the model on the training data will run the data through the model and make final classifications on survival for each passenger in the training set. The score returned is the percentage of correct classifications, or the accuracy.</p>

In [12]:
model.score(X_train,y_train)

0.7964071856287425

In [13]:
model.score(X_test,y_test)

0.7982062780269058

<p>Print the feature coefficients determined by the model. Which feature is most important in predicting survival on the sinking of the Titanic?</p>

In [14]:
print(list(zip(['Sex','Age','FirstClass','SecondClass'],model.coef_[0])))

[('Sex', 2.4579366382503762), ('Age', -0.03003272050963676), ('FirstClass', 2.027147125429227), ('SecondClass', 0.993091680482748)]


<h3>Predict with the Model</h3>
<p>Let’s use our model to make predictions on the survival of a few fateful passengers. Provided in the code editor is information for 3rd class passenger Jack and 1st class passenger Rose, stored in NumPy arrays. The arrays store 4 feature values, in the following order:

Sex, represented by a 0 for male and 1 for female
Age, represented as an integer in years
FirstClass, with a 1 indicating the passenger is in first class
SecondClass, with a 1 indicating the passenger is in second class
A third array, You, is also provided in the code editor with empty feature values. Uncomment the line containing You and update the array with your information, or the information for some fictitious passenger. Make sure to enter all values as floats with a .!</p>

In [19]:
# Sample passenger features
Jack = np.array([0.0,20.0,0.0,0.0])
Rose = np.array([1.0,17.0,1.0,0.0])
Taiga = np.array([1.0,25.0,0.0,1.0])
sample_passengers = np.array([Jack,Rose,Taiga])

<p>Since our Logistic Regression model was trained on scaled feature data, we must also scale the feature data we are making predictions on. Using the StandardScaler object created earlier, apply its .transform() method to sample_passengers and save the result to sample_passengers.

Print sample_passengers to view the scaled features.</p>

In [20]:
sample_passenger = scaler.transform(sample_passengers)
print(sample_passenger)

[[-0.73186897 -0.72064353 -0.57274061 -0.49391078]
 [ 1.36636481 -0.95142745  1.74599108 -0.49391078]
 [ 1.36636481 -0.33600366 -0.57274061  2.02465717]]


<p>Who will survive, and who will sink? Use your model’s .predict() method on sample_passengers and print the result to find out.

Want to see the probabilities that led to these predictions? Call your model’s .predict_proba() method on sample_passengers and print the result. The 1st column is the probability of a passenger perishing on the Titanic, and the 2nd column is the probability of a passenger surviving the sinking (which was calculated by our model to make the final classification decision).</p>

In [21]:
predict_sirvive = model.predict(sample_passenger )
predict_sirvive_proba = model.predict_proba(sample_passenger)
print(predict_sirvive)
print(predict_sirvive_proba)

[0 1 1]
[[0.9916626 0.0083374]
 [0.0061445 0.9938555]
 [0.0537425 0.9462575]]


<p>Acoording to the prediction that I did, I(Taiga) will survive </p>
<ul>
    <li>Jack - Die (Dead:99%,Survive:0.8%)</li>
    <li>Rose - Survive (Dead:0.6%,Survive:99)